service: sendy

plugins:
  - serverless-python-requirements
  - serverless-plugin-resource-tagging

package:
  exclude:
    - ./**
    - '!src/**'

custom:
  pythonRequirements:
    dockerizePip: non-linux

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  role: ${ env:LAMBDA_ROLE }
  environment:
    GOOGLE_CHAT_WEBHOOK: ${ env:GOOGLE_CHAT_WEBHOOK }
    MYSQL_HOST: ${ env:MYSQL_HOST }
    MYSQL_PORT: ${ env:MYSQL_PORT }
    MYSQL_USER: ${ env:MYSQL_USER }
    MYSQL_PASSWORD: ${ env:MYSQL_PASSWORD }
    MYSQL_DATABASE: ${ env:MYSQL_DATABASE }
    SENDY_URL: ${ env:SENDY_URL }
    SENDY_API_KEY: ${ env:SENDY_API_KEY }
    SENDY_LIST_KEY: ${ env:SENDY_LIST_KEY }
  stackTags:
    environment: tools
    duration: temporary
  lambdaHashingVersion: 20201221

functions:
  sendy:
    handler: src/main.handler
    name: sendy
    description: updates sendy subscribers list
    memorySize: 128
    timeout: 15
    vpc:
      subnetIds:
        - subnet-4cc5f463
        - subnet-6a679c20
      securityGroupIds:
        - sg-0904d8d08276c7ed7
    events:
      - schedule:
          name: sendy-add-subscribers
          description: updates sendy subscribers list every week
          rate: cron(0 11 ? * 2 *)
          input:
            command: addSubscribers
